### ISSUE TITLE
ERROR:  Could not find a valid gem 'ruby-tensorflow' (>= 0) in any repository

### ISSUE THREAD

**Issue by nelyj** [ankurayadav/ruby-tensorflow#5]
I'm trying to install ruby-tensorflow gem, but when I execute this command: 

`gem install 'ruby-tensorflow' 
`

The console show this message: **"ERROR:  Could not find a valid gem 'ruby-tensorflow' (>= 0) in any repository"**

**Comment by ankurayadav** [comment]
@patojimenez I am not currently developing this project. For latest work on ruby tensorflow gem please follow. https://github.com/Arafatk/tensorflow.rb
